# Colors (Github Light Main)
# colors:
#   # Default colors
#   primary:
#     background: "0xffffff"
#     foreground: "0x4d5566"
#   # Normal colors
#   normal:
#     black: "0x24292e"
#     red: "0xd73a49"
#     green: "0x22863a"
#     yellow: "0xb08800"
#     blue: "0x0366d6"
#     magenta: "0x6f42c1"
#     cyan: "0x1b7c83"
#     white: "0x4d5566"
#   # Bright colors
#   bright:
#     black: "0x586069"
#     red: "0xcb2431"
#     green: "0x28a745"
#     yellow: "0xdbab09"
#     blue: "0x2188ff"
#     magenta: "0x8a63d2"
#     cyan: "0x1b7c83"
#     white: "0x4d5566"
#   indexed_colors:
#     - { index: 16, color: "0xd18616" }
#     - { index: 17, color: "0xcb2431" }

# Colors (Github Light Alt)
# colors:
#   # Default colors
#   primary:
#     background: '0xffffff'
#     foreground: '0x586069'

#   # Normal colors
#   normal:
#     black: '0x697179'
#     red: '0xd03d3d'
#     green: '0x14ce14'
#     yellow: '0x949800'
#     blue: '0x0451a5'
#     magenta: '0xbc05bc'
#     cyan: '0x0598bc'
#     white: '0x586069'

#   # Bright colors
#   bright:
#     black: '0x666666'
#     red: '0xcd3131'
#     green: '0x14ce14'
#     yellow: '0xb5ba00'
#     blue: '0x0451a5'
#     magenta: '0xbc05bc'
#     cyan: '0x0598bc'
#     white: '0x586069'

#   indexed_colors:
#     - { index: 16, color: '0xd18616' }
#     - { index: 17, color: '0xcd3131' }

# Colors (Photon)
# colors:
#   primary:
#     background: "#262626"
#     foreground: "#c6c6c6"
#   cursor:
#     text: "#262626"
#     cursor: "#c6c6c6"
#   normal:
#     black: "#262626"
#     red: "#F88D8B"
#     green: "#5BC186"
#     yellow: "#D6AA5C"
#     blue: "#5EB6F4"
#     magenta: "#D098FA"
#     cyan: "#B6B65A"
#     white: "#626262"
#   bright:
#     black: "#767676"
#     red: "#FCC6C5"
#     green: "#ADE0C2"
#     yellow: "#EBD4AE"
#     blue: "#AEDAF9"
#     magenta: "#E8CCFC"
#     cyan: "#DADAAD"

# Colors (AntiPhoton)
# colors:
#   primary:
#     background: "#FFFFFF"
#     foreground: "#121212"
#   cursor:
#     text: "#121212"
#     cursor: "#FFFFFF"
#   normal:
#     black: "#121212"
#     red: "#E72222"
#     green: "#0F8841"
#     yellow: "#7A790E"
#     blue: "#0A7BC2"
#     magenta: "#9F4FDA"
#     cyan: "#A66801"
#     white: "#949494"
#   bright:
#     black: "#6C6C6C"
#     red: "#FF5E3D"
#     green: "#00AB47"
#     yellow: "#9a9800"
#     blue: "#0099FA"
#     magenta: "#C06CFF"
#     cyan: "#D18200"
#     white: "#FFFFFF"

# # Colors (Catppuccin)
# colors:
#   primary:
#     background: "#1E1E2E"
#     foreground: "#CDD6F4"
#   # cursor:
#   #   text: "#1E1E2E"
#   #   cursor: "#CDD6F4"
#   normal:
#     black: "#1E1E2E"
#     red: "#F38BA8"
#     green: "#A6E3A1"
#     yellow: "#F9E2AF"
#     blue: "#89B4FA"
#     magenta: "#CBA6F7"
#     cyan: "#94E2D5"
#     white: "#CDD6F4"
#   bright:
#     black: "#1E1E2E"
#     red: "#F38BA8"
#     green: "#A6E3A1"
#     yellow: "#F9E2AF"
#     blue: "#89B4FA"
#     magenta: "#CBA6F7"
#     cyan: "#94E2D5"
#     white: "#CDD6F4"

# Colors (Everforest)
# colors:
#   primary:
#     background: "#2A333A"
#     foreground: "#D4C6A7"
#   cursor:
#     text: "#2A333A"
#     cursor: "#D4C6A7"
#   normal:
#     black: "#2A333A"
#     red: "#F27983"
#     green: "#76C38E"
#     yellow: "#DBB976"
#     blue: "#72BCB2"
#     magenta: "#DD95B8"
#     cyan: "#A2C278"
#     white: "#7F8F85"
#   bright:
#     black: "#767676"
#     red: "#FCC6C5"
#     green: "#ADE0C2"
#     yellow: "#EBD4AE"
#     blue: "#AEDAF9"
#     magenta: "#E8CCFC"
#     cyan: "#DADAAD"

# Colors (Iceberg Dark)
# colors:
#   # Default colors
#   primary:
#     background: '#161821'
#     foreground: '#d2d4de'
#   # Normal colors
#   normal:
#     black:   '#161821'
#     red:     '#e27878'
#     green:   '#b4be82'
#     yellow:  '#e2a478'
#     blue:    '#84a0c6'
#     magenta: '#a093c7'
#     cyan:    '#89b8c2'
#     white:   '#c6c8d1'
#   # Bright colors
#   bright:
#     black:   '#6b7089'
#     red:     '#e98989'
#     green:   '#c0ca8e'
#     yellow:  '#e9b189'
#     blue:    '#91acd1'
#     magenta: '#ada0d3'
#     cyan:    '#95c4ce'
#     white:   '#d2d4de'

# Colors (Iceberg Light)
# colors:
#   # Default colors
#   primary:
#     # background: '#e8e9ec'
#     background: "#ffffff"
#     foreground: "#33374c"
#   # Normal colors
#   normal:
#     black: "#dcdfe7"
#     red: "#cc517a"
#     green: "#668e3d"
#     yellow: "#c57339"
#     blue: "#2d539e"
#     magenta: "#7759b4"
#     cyan: "#3f83a6"
#     white: "#33374c"
#   # Bright colors
#   bright:
#     black: "#8389a3"
#     red: "#cc3768"
#     green: "#598030"
#     yellow: "#b6662d"
#     blue: "#22478e"
#     magenta: "#6845ad"
#     cyan: "#327698"
#     white: "#262a3f"

# Colors (Hybrid)
# colors:
#   primary:
#     background: '0x1d1f21'
#     foreground: '0xc4c8c6'
#   # cursor:
#   #   text: '0x1d1f21'
#   #   cursor: '0x6f7881'
#   normal:
#     black: '0x1d1f21'
#     red: '0xd55e64'
#     green: '0xb2bf5b'
#     yellow: '0xf4c666'
#     blue: '0x7da2c1'
#     magenta: '0xb691be'
#     cyan: '0x80c0b7'
#     white: '0xc4c8c6'
#   bright:
#     black: '0x4c4c4c'
#     red: '0xd55e64'
#     green: '0xb2bf5b'
#     yellow: '0xf4c666'
#     blue: '0x7da2c1'
#     magenta: '0xb691be'
#     cyan: '0x80c0b7'
#     white: '0xc4c8c6'

# # Colors (Tender)
# colors:
#   primary:
#     # background: "#282828" # default
#     background: "#1d1d1d" # darker
#     # background: "#141414" # darkest
#     foreground: "#eeeeee"
#   # cursor:
#   #   text: "#282828"
#   #   cursor: "#bbbbbb"
#   normal:
#     black: "#282828"
#     red: "#f43753"
#     green: "#c9d05c"
#     yellow: "#ffc24b"
#     blue: "#b3deef"
#     magenta: "#d3b987"
#     cyan: "#73cef4"
#     white: "#eeeeee"
#   bright:
#     black: "#4c4c4c"
#     red: "#f43753"
#     green: "#c9d05c"
#     yellow: "#ffc24b"
#     blue: "#b3deef"
#     magenta: "#d3b987"
#     cyan: "#73cef4"
#     white: "#feffff"

## Colors (Poimandres)
#colors:
#  # Default colors
#  primary:
#    background: "0x1b1e28"
#    # background: "0x1E1E1E"
#    foreground: "0xa6accd"
#  # Cursor colors
#  cursor:
#    text: CellBackground
#    cursor: CellForeground
#  # Search colors
#  #
#  # Colors used for the search bar and match highlighting.
#  search:
#    # Allowed values are CellForeground/CellBackground, which reference the
#    # affected cell, or hexadecimal colors like #ff00ff.
#    matches:
#      # foreground: "0x1b1e28"
#      foreground: "0x1E1E1E"
#      background: "0xadd7ff"
#    focused_match:
#      # foreground: "0x1b1e28"
#      foreground: "0x1E1E1E"
#      background: "0xadd7ff"
#    bar:
#      # foreground: "0x1b1e28"
#      foreground: "0x1E1E1E"
#      background: "0xadd7ff"
#  # Selection colors
#  #
#  # Colors which should be used to draw the selection area.
#  #
#  # Allowed values are CellForeground/CellBackground, which reference the
#  # affected cell, or hexadecimal colors like #ff00ff.
#  selection:
#    text: CellForeground
#    background: "0x303340"
#  # Vi mode cursor colors
#  #
#  # Colors for the cursor when the vi mode is active.
#  #
#  # Allowed values are CellForeground/CellBackground, which reference the
#  # affected cell, or hexadecimal colors like #ff00ff.
#  vi_mode_cursor:
#    text: CellBackground
#    cursor: CellForeground
#  # Normal colors
#  normal:
#    # black: "0x1b1e28"
#    black: "0x1E1E1E"
#    red: "0xd0679d"
#    green: "0x5de4c7"
#    yellow: "0xfffac2"
#    blue: "0x89ddff"
#    magenta: "0xfcc5e9"
#    cyan: "0xadd7ff"
#    white: "0xffffff"
#  # Bright colors
#  bright:
#    black: "0xa6accd"
#    red: "0xd0679d"
#    green: "0x5de4c7"
#    yellow: "0xfffac2"
#    blue: "0xadd7ff"
#    magenta: "0xfae4fc"
#    cyan: "0x89ddff"
#    white: "0xffffff"

## Colors (Poimandres Storm)
#colors:
#  # Default colors
#  primary:
#    background: "0x252b37"
#    foreground: "0xa6accd"
#  # Cursor colors
#  cursor:
#    text: CellBackground
#    cursor: CellForeground
#  # Search colors
#  #
#  # Colors used for the search bar and match highlighting.
#  search:
#    # Allowed values are CellForeground/CellBackground, which reference the
#    # affected cell, or hexadecimal colors like #ff00ff.
#    matches:
#      foreground: "0x1b1e28"
#      background: "0xadd7ff"
#    focused_match:
#      foreground: "0x1b1e28"
#      background: "0xadd7ff"
#    bar:
#      foreground: "0x1b1e28"
#      background: "0xadd7ff"
#  # Selection colors
#  #
#  # Colors which should be used to draw the selection area.
#  #
#  # Allowed values are CellForeground/CellBackground, which reference the
#  # affected cell, or hexadecimal colors like #ff00ff.
#  selection:
#    text: CellForeground
#    background: "0x303340"
#  # Vi mode cursor colors
#  #
#  # Colors for the cursor when the vi mode is active.
#  #
#  # Allowed values are CellForeground/CellBackground, which reference the
#  # affected cell, or hexadecimal colors like #ff00ff.
#  vi_mode_cursor:
#    text: CellBackground
#    cursor: CellForeground
#  # Normal colors
#  normal:
#    black: "0x252b37"
#    red: "0xd0679d"
#    green: "0x5de4c7"
#    yellow: "0xfffac2"
#    blue: "0x89ddff"
#    magenta: "0xfae4fc"
#    cyan: "0xadd7ff"
#    white: "0xffffff"
#  # Bright colors
#  bright:
#    black: "0xa6accd"
#    red: "0xd0679d"
#    green: "0x5de4c7"
#    yellow: "0xfffac2"
#    blue: "0xadd7ff"
#    cyan: "0x89ddff"
#    magenta: "0xfcc5e9"
#    white: "0xffffff"

## Colors (Gruvbox dark)
# colors:
#   primary:
#     # hard contrast background - '#1d2021'
#     background: &gruvbox_dark_bg "#282828"
#     # soft contrast background - '#32302f'
#     foreground: "#ebdbb2"
#     bright_foreground: "#fbf1c7"
#     dim_foreground: "#a89984"
#   cursor:
#     text: CellBackground
#     cursor: CellForeground
#   vi_mode_cursor:
#     text: CellBackground
#     cursor: CellForeground
#     search:
#       matches:
#         foreground: "#000000"
#         background: "#ffffff"
#       focused_match:
#         foreground: CellBackground
#         background: CellForeground
#       bar:
#         background: ""
#         foreground: ""
#     line_indicator:
#       foreground: None
#       background: None
#   selection:
#     text: CellBackground
#     background: CellForeground
#   bright:
#     black: "#928374"
#     red: "#fb4934"
#     green: "#b8bb26"
#     yellow: "#fabd2f"
#     blue: "#83a598"
#     magenta: "#d3869b"
#     cyan: "#8ec07c"
#     white: "#ebdbb2"
#   normal:
#     black: *gruvbox_dark_bg
#     red: "#cc241d"
#     green: "#98971a"
#     yellow: "#d79921"
#     blue: "#458588"
#     magenta: "#b16286"
#     cyan: "#689d6a"
#     white: "#a89984"
#   dim:
#     black: "#32302f"
#     red: "#9d0006"
#     green: "#79740e"
#     yellow: "#b57614"
#     blue: "#076678"
#     magenta: "#8f3f71"
#     cyan: "#427b58"
#     white: "#928374"
#   #   indexed_colors: []

# # Colors (Gruvbox Material)
# colors:
#   primary:
#     # hard contrast background - '#1d2021'
#     # background: &gruvbox_dark_bg '#282828'
#     background: &gruvbox_dark_bg "0x1E1E1E" # darker
#     # soft contrast background - '#32302f'
#     foreground: "#D6BE93"
#     bright_foreground: "#fbf1c7"
#     dim_foreground: "#a89984"
#   cursor:
#     text: CellBackground
#     cursor: CellForeground
#   vi_mode_cursor:
#     text: CellBackground
#     cursor: CellForeground
#     search:
#       matches:
#         foreground: "#000000"
#         background: "#ffffff"
#       focused_match:
#         foreground: CellBackground
#         background: CellForeground
#       bar:
#         background: ""
#         foreground: ""
#     line_indicator:
#       foreground: None
#       background: None
#   selection:
#     text: CellBackground
#     background: CellForeground
#   bright:
#     black: "#928374"
#     red: "#fb4934"
#     green: "#b8bb26"
#     yellow: "#fabd2f"
#     blue: "#83a598"
#     magenta: "#d3869b"
#     cyan: "#8ec07c"
#     white: "#ebdbb2"
#   normal:
#     black: *gruvbox_dark_bg
#     red: "#F55E5D"
#     green: "#A5B859"
#     yellow: "#DDA548"
#     blue: "#7DAEA3"
#     magenta: "#D37D97"
#     cyan: "#80B77D"
#     white: "#D6BE93"
#   # dim:
#   #   black: "#32302f"
#   #   red: "#9d0006"
#   #   green: "#79740e"
#   #   yellow: "#b57614"
#   #   blue: "#076678"
#   #   magenta: "#8f3f71"
#   #   cyan: "#427b58"
#   #   white: "#928374"
#   #   indexed_colors: []

## gruvbox_light: &gruvbox_light
# primary:
#   # hard contrast: background = '0xf9f5d7'
#   background: "0xfbf1c7"
#   # soft contrast: background = '0xf2e5bc'
#   foreground: "0x3c3836"
# normal:
#   black: "0xfbf1c7"
#   red: "0xcc241d"
#   green: "0x98971a"
#   yellow: "0xd79921"
#   blue: "0x458588"
#   magenta: "0xb16286"
#   cyan: "0x689d6a"
#   white: "0x7c6f64"
# bright:
#   black: "0x928374"
#   red: "0x9d0006"
#   green: "0x79740e"
#   yellow: "0xb57614"
#   blue: "0x076678"
#   magenta: "0x8f3f71"
#   cyan: "0x427b58"
#   white: "0x3c3836"

# Colors (Zenbones)
# colors:
#   # Default colors
#   primary:
#     background: '#F0EDEC'
#     foreground: '#2C363C'
#   # Normal colors
#   normal:
#     black:   '#2C363C'
#     red:     '#A8334C'
#     green:   '#617437'
#     yellow:  '#944927'
#     blue:    '#286486'
#     magenta: '#88507D'
#     cyan:    '#3B8992'
#     white:   '#F0EDEC'
#   # Bright colors
#   bright:
#     black:   '#44525B'
#     red:     '#9C2842'
#     green:   '#55672A'
#     yellow:  '#87411E'
#     blue:    '#1F5A7A'
#     magenta: '#864079'
#     cyan:    '#2F7C85'
#     white:   '#DCD2CE'

## Colors (one light)
# colors:
#   primary:
#     background: "#fafafa"
#     foreground: "#383a42"
#   cursor:
#     text: CellBackground
#     cursor: "#526eff" # syntax-cursor-color
#   selection:
#     text: CellForeground
#     background: "#e5e5e6" # syntax-selection-color
#   normal:
#     black: "#696c77" # mono-2
#     red: "#e45649" # red 1
#     green: "#50a14f"
#     yellow: "#c18401" # orange 2
#     blue: "#4078f2"
#     magenta: "#a626a4"
#     cyan: "#0184bc"
#     white: "#a0a1a7" # mono-3
