colors:
  primary:
    background: "#ffffff" # darker
    foreground: "#000000"
  # cursor:
  #   text: "#ffffff"
  #   cursor: "#6B6A64"
  normal:
    black: "#000000"
    red: "#AC002A"
    green: "#006227"
    yellow: "#7A4900"
    blue: "#543DBB"
    magenta: "#931099"
    cyan: "#005B7C"
    white: "#F5F5F3"
  bright:
    black: "#363636"
    red: "#c1002f"
    green: "#006e2c"
    yellow: "#895200"
    blue: "#5f45d2"
    magenta: "#a512ac"
    cyan: "#00668c"
    white: "#ffffff"
