[colors.bright]
black = "#33322F"
blue = "#5f45d2"
cyan = "#00668c"
green = "#006e2c"
magenta = "#9c28a2"
red = "#c1002f"
white = "#F6F6F0"
yellow = "#895200"

[colors.normal]
black = "#000000"
blue = "#543DBB"
cyan = "#005B7C"
green = "#006227"
magenta = "#8b2490"
red = "#AC002A"
white = "#ECECE4"
yellow = "#7A4900"

[colors.primary]
background = "#F6F6F0"
foreground = "#000000"
