colors:
  primary:
    background: "#111e29" # darker
    foreground: "#ffffff"
  # cursor:
  #   text: "#111e29"
  #   cursor: "#c8d1d8"
  normal:
    black: "#111e29"
    red: "#ff9aa0"
    green: "#5bfeb7"
    yellow: "#d0ffbe"
    blue: "#bfaaff"
    magenta: "#ff8cf4"
    cyan: "#9cd6ff"
    white: "#c8d1d8"
  bright:
    black: "#1f3344"
    red: "#ffbcc0"
    green: "#92fecf"
    yellow: "#e0ffd4"
    blue: "#d4c6ff"
    magenta: "#ffb2f8"
    cyan: "#bde4ff"
    white: "#ffffff"
