# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#font
[font]
size = 13.5

[font.normal]
family = "NotoSansM Nerd Font"
style = "Regular"

[font.bold]
family = "NotoSansM Nerd Font"
style = "Bold"

[font.offset]
x = 0
y = 0
