#!/usr/bin/env bash
# mkdir -p ~/.config/nvim/plugin
# mkdir -p ~/.config/nvim/lua
mkdir -p ~/.config/nvim/after/plugin

# link everything
# for f in `find . -regex ".*\.vim$\|.*\.lua$"`; do

for f in `find . -name "*.vim" -o -name "*.lua"`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/.dotfiles/config/nvim/$f ~/.config/nvim/$f
done
